# File: .github/workflows/workflow.yml

name: Run Azure Login with OIDC
on: 
    workflow_dispatch:
    
permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: arc-runner-set
    steps:
      - name: Install Azure cli
        run: |
          sudo apt-get update
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg -y
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli -y
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - run: |
          az account show
          sudo az aks install-cli
          az aks get credentials -g ${{ secrets.AKS_RESOURCE_GROUP }} -n ${{ secrets.AKS_NAME }}
          kubectl get pods -A
 
      #- name: Azure CLI script
      #  uses: azure/CLI@v1
      #  with:
      #    azcliversion: latest
      #    inlineScript: |
      #      az account show
